const data = {
  products: [
    {
      name: 'officeware',
      slug: 'officeware',
      category: 'trousers',
      image: 'images/officeware.jpg',
      price: '100',
      brand: 'vitech',
      rating: '4.5',
      numReview: '8',
      countInStock: '20',
      description: 'new jens trousers',
    },

    {
      name: 'overall',
      slug: 'overall',
      category: 'overall',
      image: 'images/overall.jpg',
      price: '100',
      brand: 'vitech',
      rating: '4.5',
      numReview: '8',
      countInStock: '20',
      description: 'new ladies overall dress',
    },

    {
      name: 'ladies',
      slug: 'ladies',
      category: 'ladies',
      image: 'images/ladies.jpg',
      price: '100',
      brand: 'vitech',
      rating: '4.5',
      numReview: '8',
      countInStock: '20',
      description: 'new set dress',
    },

    {
      name: 'nice',
      slug: 'nice',
      category: 'nice',
      image: 'images/nice.jpg',
      price: '100',
      brand: 'vitech',
      rating: '4.5',
      numReview: '8',
      countInStock: '20',
      description: 'new set dress',
    },

    {
      name: 'top',
      slug: 'top',
      category: 'top',
      image: 'images/top.jpg',
      price: '100',
      brand: 'vitech',
      rating: '4.5',
      numReview: '8',
      countInStock: '20',
      description: 'new top dress',
    },

    {
      name: 'overall',
      slug: 'overall',
      category: 'overall',
      image: 'images/overall.jpg',
      price: '100',
      brand: 'vitech',
      rating: '4.5',
      numReview: '8',
      countInStock: '20',
      description: 'new top long dress',
    },

    {
      name: 'ladies',
      slug: 'ladies',
      category: 'ladies',
      image: 'images/ladies.jpg',
      price: '100',
      brand: 'vitech',
      rating: '4.5',
      numReview: '8',
      countInStock: '20',
      description: 'new top2 dress',
    },
    {
      name: 'nice',
      slug: 'nice',
      category: 'nice',
      image: 'images/nice.jpg',
      price: '100',
      brand: 'vitech',
      rating: '4.5',
      numReview: '8',
      countInStock: '20',
      description: 'new tops dress',
    },

    {
      name: 'officeware',
      slug: 'officeware',
      category: 'officeware',
      image: 'images/officeware.jpg',
      price: '100',
      brand: 'vitech',
      rating: '4.5',
      numReview: '8',
      countInStock: '20',
      description: 'new tops short dress',
    },

    {
      name: 'sale',
      slug: 'sale',
      category: 'sale',
      image: 'images/sale.jpg',
      price: '100',
      brand: 'vitech',
      rating: '4.5',
      numReview: '8',
      countInStock: '20',
      description: 'new set dress',
    },

    {
      name: 'ladies',
      slug: 'ladies',
      category: 'ladies',
      image: 'images/ladies.jpg',
      price: '100',
      brand: 'vitech',
      rating: '4.5',
      numReview: '8',
      countInStock: '20',
      description: 'new set dress',
    },

    {
      name: 'overall',
      slug: 'overall',
      category: 'overall',
      image: 'images/overall.jpg',
      price: '100',
      brand: 'vitech',
      rating: '4.5',
      numReview: '8',
      countInStock: '20',
      description: 'new set dress',
    },
  ],
};

export default data;
